# Generated by Django 4.1.2 on 2022-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#000000', 'черный'), ('#808080', 'серый'), ('#0000FF', 'синий'), ('#FF0000', 'красный'), ('#008000', 'зеленый'), ('#FFFF00', 'желтый'), ('#A52A2A', 'коричневый'), ('#FFFFFF', 'белый')], max_length=7, unique=True),
        ),
    ]
