# Generated by Django 4.1.2 on 2022-10-25 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#000000', 'черный'), ('#808080', 'серый'), ('#0000FF', 'синий'), ('#FF0000', 'красный'), ('#008000', 'зеленый'), ('#FFFF00', 'желтый'), ('#A52A2A', 'коричневый'), ('#FFFFFF', 'белый')], max_length=7, unique=True, verbose_name='Цвет иконки'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название тэга'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$')], verbose_name='Пока не понятно'),
        ),
    ]
