# Generated by Django 4.1.2 on 2022-10-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngedientAmount',
            new_name='IngredientAmount',
        ),
    ]
