# Generated by Django 4.1.2 on 2022-11-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_tag_color_alter_tag_name_shoppingcart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipe.ingredients', verbose_name='Ингридиент'),
        ),
    ]
