# Generated by Django 4.1.2 on 2022-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_ingredientamount_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепты для покупки', 'verbose_name_plural': 'Рецепты для покупок'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='images_recipe', verbose_name='Картинка рецепта'),
        ),
    ]
